sudo: false
language: cpp
compiler:
  - clang

addons:
  apt:
    sources:
    - kubuntu-backports
    packages:
    - cmake

before_install:
  - pip install --user cpp-coveralls


script:
  - mkdir build
  - cd build
  - cmake ../ -DCI_BUILD=TRUE -DCOVERAGE=TRUE -DBUILD_TESTS=TRUE
  - make "$@"
  - cd ..
  - cd build
  - ./tests

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'

notifications:
  email:
    - info@franciscotufro.com
