language: cpp
compiler:
  - clang

before_install:
  - pip install --user cpp-coveralls

script:
  - cmake -DCOVERAGE=TRUE -DBUILD_TESTS=TRUE
  - make "$@"
  - ./tests

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'

notifications:
  email:
    - info@franciscotufro.com