language: cpp
compiler:
  - clang

before_install:
  - pip install --user cpp-coveralls
  - sudo add-apt-repository --yes ppa:kalakris/cmake
  - sudo apt-get update -qq
  - sudo apt-get install cmake

script:
  - mkdir build
  - cd build
  - cmake ../ -DCOVERAGE=TRUE -DBUILD_TESTS=TRUE
  - make "$@"
  - cd ..
  - cd build
  - ./tests

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'

notifications:
  email:
    - info@franciscotufro.com